neuron :
  use_std : True
  U_SE_val : 0.37
  tau_rec_std_ms : 350.0
  alpha1 : True
  alpha2 : 0.3
  reset_potential : True
  tau_stdp_ms : 20
  plasticity : rate
  recharge : 0
background:
  background_poisson : 2
  poisson_amplitude : 0.3
target_rate : 3
name : sfa_rate