python plotting/fig1/intro.py &
python plotting/fig2/replay.py &
python plotting/fig3/cued_recall.py &
python plotting/fig4/wta.py &
python plotting/fig5-6-S2/assembly_specificity_separate.py &
python plotting/fig7/contamination.py &
python plotting/fig8/eigenspectra.py &
python plotting/figS1/fig_persistent.py &
python plotting/figS2/supp_suscept.py &
python plotting/figS4/overlaps_completion.py &