neuron :
  use_std : True
  alpha1 : False
  alpha2 : 0.3
  reset_potential : True
  tau_stdp_ms : 20
  plasticity : rate
  recharge : 0
background:
  background_poisson : 2
  poisson_amplitude : 0.3
target_rate : 3
name : std_rate