run:
  learning_rate : 0.
  simulation_time : 1000
  state_variables : null
  save_weights : False
  chunk_size : 100
  inhf_setting: 1.2
  taui_setting: 12
init_matrix : null
stimulus : null
name : spontaneous_short_set5_